urlData:
  baseURL: https://thetestingworldapi.com/api/
  studentsDetailsEndpoint: studentsDetails/
testData:
  studentFirstName: Gandalf
  studentMiddleName: GreyMan
  studentLastName: Grey
  studentDateOfBirth: 10/12/1035